[colors]
background = "#FFFCF0"
foreground = "#403E3C"
cursor = "#100F0F"
cursor_text = "#FFFCF0"
selection = "#DAD8CE"
selection_text = "#100F0F"
black = "#100F0F"
red = "#AF3029"
green = "#81a306"
yellow = "#AD8301"
blue = "#205EA6"
magenta = "#A02F6F"
cyan = "#24837B"
white = "#100F0F"
light_black = "#878580"
light_red = "#D14D41"
light_green = "#879A39"
light_yellow = "#D0A215"
light_blue = "#3e93f6"
light_magenta = "#de7777"
light_cyan = "#3AA99F"
light_white = "#FFFCF0"
